import {boolean, text, withKnobs} from '@storybook/addon-knobs/react';
import {storiesOf} from '@storybook/react-native';
import React from 'react';
import {ContactsList, IContactListItem} from '../../App/components/ContactsList';
import {Colors} from '../../App/theme';
import CenterView from '../CenterView';

const containerStyle = {
	backgroundColor: Colors.white,
	paddingHorizontal: 0,
	paddingVertical: 0,
};

export const DUMMY_CONTACTS_LIST = [
	{name: 'Delilah Thorman', avatarURL: 'https://placeimg.com/100/100/any'},
	{name: 'Roselee Coltharp', avatarURL: 'https://placeimg.com/101/101/any'},
	{name: 'Felicia Spinner', avatarURL: 'https://placeimg.com/102/102/any'},
	{name: 'Kiana Neher', avatarURL: 'https://placeimg.com/103/103/any'},
	{name: 'Gale Schwantes', avatarURL: 'https://placeimg.com/104/104/any'},
	{name: 'Norine Lawhead', avatarURL: 'https://placeimg.com/105/105/any'},
	{name: 'Augustine Alberti', avatarURL: 'https://placeimg.com/106/106/any'},
	{name: 'Herbert Bickett', avatarURL: 'https://placeimg.com/107/107/any'},
	{name: 'Dusti Carone', avatarURL: 'https://placeimg.com/108/108/any'},
	{name: 'Latoria Brueggeman', avatarURL: 'https://placeimg.com/109/109/any'},
	{name: 'Rosaline Finger', avatarURL: 'https://placeimg.com/110/110/any'},
	{name: 'Yolonda Rodda', avatarURL: 'https://placeimg.com/111/111/any'},
	{name: 'Kizzy Schreier', avatarURL: 'https://placeimg.com/112/112/any'},
	{name: 'Myra Gabel', avatarURL: 'https://placeimg.com/113/113/any'},
	{name: 'Maura Jolin', avatarURL: 'https://placeimg.com/114/114/any'},
	{name: 'Maximina Tuten', avatarURL: 'https://placeimg.com/115/115/any'},
	{name: 'Abigail Kopacz', avatarURL: 'https://placeimg.com/116/116/any'},
	{name: 'August Houghtaling', avatarURL: 'https://placeimg.com/117/117/any'},
	{name: 'Diann Volkmann', avatarURL: 'https://placeimg.com/118/118/any'},
	{name: 'Lourdes Eis', avatarURL: 'https://placeimg.com/119/119/any'},
	{name: 'Willetta Winsor', avatarURL: 'https://placeimg.com/120/120/any'},
	{name: 'Maryellen Zaccaria', avatarURL: 'https://placeimg.com/121/121/any'},
	{name: 'Sarai Selley', avatarURL: 'https://placeimg.com/122/122/any'},
	{name: 'Jenna Pancoast', avatarURL: 'https://placeimg.com/123/123/any'},
	{name: 'Tilda Mayor', avatarURL: 'https://placeimg.com/124/124/any'},
	{name: 'Sharell Watchman', avatarURL: 'https://placeimg.com/125/125/any'},
	{name: 'Felipe Hollie', avatarURL: 'https://placeimg.com/126/126/any'},
	{name: 'Dorthey Schlachter', avatarURL: 'https://placeimg.com/127/127/any'},
	{name: 'Santa Levy', avatarURL: 'https://placeimg.com/128/128/any'},
	{name: 'Audrey Hartley', avatarURL: 'https://placeimg.com/129/129/any'},
	{name: 'Son Friday', avatarURL: 'https://placeimg.com/130/130/any'},
	{name: 'Elfrieda Carollo', avatarURL: 'https://placeimg.com/131/131/any'},
	{name: 'Benita Ayers', avatarURL: 'https://placeimg.com/132/132/any'},
	{name: 'Ludie Cogley', avatarURL: 'https://placeimg.com/133/133/any'},
	{name: 'Shantel Bedolla', avatarURL: 'https://placeimg.com/134/134/any'},
	{name: 'Eileen Zaragosa', avatarURL: 'https://placeimg.com/135/135/any'},
	{name: 'Milford Yarnall', avatarURL: 'https://placeimg.com/136/136/any'},
	{name: 'Stanley Sater', avatarURL: 'https://placeimg.com/137/137/any'},
	{name: 'Carlena Addison', avatarURL: 'https://placeimg.com/138/138/any'},
	{name: 'Aida Swaney', avatarURL: 'https://placeimg.com/139/139/any'},
	{name: 'Jina Barcia', avatarURL: 'https://placeimg.com/140/140/any'},
	{name: 'Gail Fullwood', avatarURL: 'https://placeimg.com/141/141/any'},
	{name: 'Tosha Carder', avatarURL: 'https://placeimg.com/142/142/any'},
	{name: 'Vera Rosa', avatarURL: 'https://placeimg.com/143/143/any'},
	{name: 'Kendall Phenix', avatarURL: 'https://placeimg.com/144/144/any'},
	{name: 'Carlo Rosenbaum', avatarURL: 'https://placeimg.com/145/145/any'},
	{name: 'Abby Zinke', avatarURL: 'https://placeimg.com/146/146/any'},
	{name: 'Ruben Kissane', avatarURL: 'https://placeimg.com/147/147/any'},
	{name: 'Janessa Mechling', avatarURL: 'https://placeimg.com/148/148/any'},
	{name: 'Mariel Dresel', avatarURL: 'https://placeimg.com/149/149/any'},
	{name: 'Jodi Garton', avatarURL: 'https://placeimg.com/150/150/any'},
	{name: 'Yolande Mccullum', avatarURL: 'https://placeimg.com/151/151/any'},
	{name: 'Tamara Mayson', avatarURL: 'https://placeimg.com/152/152/any'},
	{name: 'Briana Santillo', avatarURL: 'https://placeimg.com/153/153/any'},
	{name: 'Elane Boyd', avatarURL: 'https://placeimg.com/154/154/any'},
	{name: 'Tawny Gruver', avatarURL: 'https://placeimg.com/155/155/any'},
	{name: 'Portia Winfrey', avatarURL: 'https://placeimg.com/156/156/any'},
	{name: 'Jorge Krell', avatarURL: 'https://placeimg.com/157/157/any'},
	{name: 'Christie Contos', avatarURL: 'https://placeimg.com/158/158/any'},
	{name: 'Megan Tiggs', avatarURL: 'https://placeimg.com/159/159/any'},
	{name: 'Brooke Felts', avatarURL: 'https://placeimg.com/160/160/any'},
	{name: 'Maximo Lacher', avatarURL: 'https://placeimg.com/161/161/any'},
	{name: 'Soo Chason', avatarURL: 'https://placeimg.com/162/162/any'},
	{name: 'Tabatha Yant', avatarURL: 'https://placeimg.com/163/163/any'},
	{name: 'Wen Napoli', avatarURL: 'https://placeimg.com/164/164/any'},
	{name: 'Kandace Lucas', avatarURL: 'https://placeimg.com/165/165/any'},
	{name: 'Kali Gerber', avatarURL: 'https://placeimg.com/166/166/any'},
	{name: 'Marybelle Pulsifer', avatarURL: 'https://placeimg.com/167/167/any'},
	{name: 'Dorine Averette', avatarURL: 'https://placeimg.com/168/168/any'},
	{name: 'Jamika Coan', avatarURL: 'https://placeimg.com/169/169/any'},
	{name: 'Lovetta Lesko', avatarURL: 'https://placeimg.com/170/170/any'},
	{name: 'Danyell Bevacqua', avatarURL: 'https://placeimg.com/171/171/any'},
	{name: 'Hiram Eide', avatarURL: 'https://placeimg.com/172/172/any'},
	{name: 'Kymberly Durrell', avatarURL: 'https://placeimg.com/173/173/any'},
	{name: 'Lino Linville', avatarURL: 'https://placeimg.com/174/174/any'},
	{name: 'Angelika Locher', avatarURL: 'https://placeimg.com/175/175/any'},
	{name: 'Ronald Lightner', avatarURL: 'https://placeimg.com/176/176/any'},
	{name: 'Kimbery Puffer', avatarURL: 'https://placeimg.com/177/177/any'},
	{name: 'Geraldo Arcand', avatarURL: 'https://placeimg.com/178/178/any'},
	{name: 'Ryan Brackins', avatarURL: 'https://placeimg.com/179/179/any'},
	{name: 'Margy Canter', avatarURL: 'https://placeimg.com/180/180/any'},
	{name: 'Leandro Pouncey', avatarURL: 'https://placeimg.com/181/181/any'},
	{name: 'Teddy Decola', avatarURL: 'https://placeimg.com/182/182/any'},
	{name: 'Viola Roache', avatarURL: 'https://placeimg.com/183/183/any'},
	{name: 'Gaynell Lesniak', avatarURL: 'https://placeimg.com/184/184/any'},
	{name: 'Khalilah Steckler', avatarURL: 'https://placeimg.com/185/185/any'},
	{name: 'Lakenya Timmerman', avatarURL: 'https://placeimg.com/186/186/any'},
	{name: 'Ivy Mansker', avatarURL: 'https://placeimg.com/187/187/any'},
	{name: 'Jacob Dederick', avatarURL: 'https://placeimg.com/188/188/any'},
	{name: 'Randee Guertin', avatarURL: 'https://placeimg.com/189/189/any'},
	{name: 'Barbra Roussel', avatarURL: 'https://placeimg.com/190/190/any'},
	{name: 'Michiko Bisson', avatarURL: 'https://placeimg.com/191/191/any'},
	{name: 'Clarine Alcala', avatarURL: 'https://placeimg.com/192/192/any'},
	{name: 'Bridgett Sacks', avatarURL: 'https://placeimg.com/193/193/any'},
	{name: 'Alida Molloy', avatarURL: 'https://placeimg.com/194/194/any'},
	{name: 'Lizette Fleischman', avatarURL: 'https://placeimg.com/195/195/any'},
	{name: 'Jenni Blaisdell', avatarURL: 'https://placeimg.com/196/196/any'},
	{name: 'Adriene Corsi', avatarURL: 'https://placeimg.com/197/197/any'},
	{name: 'Enda Schmucker', avatarURL: 'https://placeimg.com/198/198/any'},
	{name: 'Terica Yeaman', avatarURL: 'https://placeimg.com/199/199/any'},
];

const contactSelectedHandler = (data: IContactListItem) => {
	alert('contactSelectedHandler: ' + data.name);
};

storiesOf('Contacts list')
	.addDecorator((getStory: any) => <CenterView style={containerStyle}>{getStory()}</CenterView>)
	.addDecorator(withKnobs)
	.add('sample', () => {
		return <ContactsList listData={DUMMY_CONTACTS_LIST} onContactSelect={contactSelectedHandler} />;
	});
